name: string_utils CI

on:
  push:
    paths:
      - string_utils/**/*.py
      - tests/**/*.py
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - string_utils/**/*.py
      - tests/**/*.py
      - .github/workflows/ci.yml
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Pythonをセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 依存関係をインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: テストを実行
      env:
        PYTHONPATH: .
      run: pytest tests/